### PR TITLE
Ready to show in mobile

### PR DESCRIPTION
**Pull request by BhautikChudasama**

### CODE REVIEW

**Comment by sahitpj** [comment]
hey @BhautikChudasama could you send me screenshots of the mobile view of the website

**Comment by BhautikChudasama** [comment]
Sure here is screenshot 

https://drive.google.com/file/d/1gwhvQ1fMNMpgxTBqmkwvJR1nhQYgXYOx/view?usp=drivesdk

https://drive.google.com/file/d/1JN-dPLonMlFQWedMaBmht86ljm_n8UeD/view?usp=drivesdk

**Comment by maryna-yanul** [comment]
I think it is really strange that hamburger menu icon, which is in the right upper corner, opens menu at the left side.

**Comment by sahitpj** [comment]
Cool, I think I am ready to merge this. Just one more thing - can you mention the parts you added/editted in order to get this by adding comments in the files. 
@BhautikChudasama

**Comment by BhautikChudasama** [comment]
Font size is changed when small screen and I can add svg of hamburger menu.
Thanks 😀

**Comment by sahitpj** [comment]
Thanks a lot @BhautikChudasama , Go ahead and add your name in the list of contributors in the community repo and make a PR 😄

**Comment by BhautikChudasama** [comment]
I've a suggestion to add service worker and manifest.json for make your site today's site (Progressive Web App) ☺️

**Comment by sahitpj** [comment]
yeah sure, open up another issue, with all the details @BhautikChudasama

**Pull request merged**
